name: MessageExamples
version: 1.0.0
description: Paper Message API examples.
# Comments
author: engineeringcode93@gmail.com
website: https://engineeringcode.tistory.com/

main: net.engineeringcode.mc.MessageExamples
api-version: 1.15

commands:

permissions:
