name: TeleportExamples
version: 1.0.0
description: Paper Teleport API examples.
# Comments
author: engineeringcode93@gmail.com
website: https://engineeringcode.tistory.com/

main: net.engineeringcode.mc.Teleport
api-version: 1.15

commands:
  teleport.teleport:
    description: Set yourself on fire.
    aliases: [teleport]
    permission: teleport.teleport
    usage: Syntax error! Simply type /teleport <target> <x> <y> <z>

permissions:
  teleport.teleport:
    description: /teleport <target> <x> <y> <z>
    default: true